"""empty message

Revision ID: 4a3ecf731c61
Revises: e20b0295a622
Create Date: 2019-05-19 17:28:04.457693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a3ecf731c61'
down_revision = 'e20b0295a622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('funcionario_ibfk_1', 'funcionario', type_='foreignkey')
    op.drop_column('funcionario', 'func_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionario', sa.Column('func_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('funcionario_ibfk_1', 'funcionario', 'funcionario', ['func_id'], ['id'])
    # ### end Alembic commands ###
