"""empty message

Revision ID: a30b97166aa3
Revises: 4a3ecf731c61
Create Date: 2019-06-26 06:59:11.810762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30b97166aa3'
down_revision = '4a3ecf731c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('image', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'image')
    # ### end Alembic commands ###
