"""empty message

Revision ID: e20b0295a622
Revises: 
Create Date: 2019-05-19 17:23:38.183768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e20b0295a622'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(length=25), nullable=False),
    sa.Column('bairro', sa.String(length=25), nullable=False),
    sa.Column('numero', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('senha_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cliente',
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('data_nasc', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('usu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usu_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('cpf'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('admin', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('usu_id', sa.Integer(), nullable=False),
    sa.Column('func_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['func_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['usu_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('nomefantasia', sa.String(length=30), nullable=False),
    sa.Column('telefone', sa.String(length=14), nullable=False),
    sa.Column('descricao', sa.Text(length=100), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('end_id', sa.Integer(), nullable=False),
    sa.Column('func_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['end_id'], ['endereco.id'], ),
    sa.ForeignKeyConstraint(['func_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('cnpj'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('estilomusical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=15), nullable=False),
    sa.Column('func_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['func_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomeevento', sa.String(length=30), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('hora_inicio', mysql.TIME(), nullable=False),
    sa.Column('hora_final', mysql.TIME(), nullable=False),
    sa.Column('descricao', sa.Text(length=100), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('est_id', sa.Integer(), nullable=False),
    sa.Column('cnpj_emp', sa.String(length=18), nullable=False),
    sa.Column('func_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cnpj_emp'], ['empresa.cnpj'], ),
    sa.ForeignKeyConstraint(['est_id'], ['estilomusical.id'], ),
    sa.ForeignKeyConstraint(['func_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_compra', sa.DateTime(), nullable=False),
    sa.Column('evt_id', sa.Integer(), nullable=False),
    sa.Column('cpf_cli', sa.String(length=14), nullable=False),
    sa.ForeignKeyConstraint(['cpf_cli'], ['cliente.cpf'], ),
    sa.ForeignKeyConstraint(['evt_id'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tipo_ingresso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lote', sa.Integer(), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('evt_id', sa.Integer(), nullable=False),
    sa.Column('func_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evt_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['func_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('itens_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_ingresso.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_compra')
    op.drop_table('tipo_ingresso')
    op.drop_table('compra')
    op.drop_table('evento')
    op.drop_table('estilomusical')
    op.drop_table('empresa')
    op.drop_table('funcionario')
    op.drop_table('cliente')
    op.drop_table('usuario')
    op.drop_table('endereco')
    # ### end Alembic commands ###
